# Support Docling Knowledge Base for Nextcloud
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: ihsanmokhlis
buy_me_a_coffee: ihsanmokhlis
# ko_fi: ihsanmokhlis
# patreon: ihsanmokhlis
# open_collective: docling-kb
# custom: ["https://your-donation-link.com"]

